# Makefile.in generated by automake 1.16.5 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2021 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/libutils
pkgincludedir = $(includedir)/libutils
pkglibdir = $(libdir)/libutils
pkglibexecdir = $(libexecdir)/libutils
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = bin/DETLSH$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(libdir)"
PROGRAMS = $(bin_PROGRAMS)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
LIBRARIES = $(lib_LIBRARIES)
AR = ar
ARFLAGS = cru
AM_V_AR = $(am__v_AR_$(V))
am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
am__v_AR_0 = @echo "  AR      " $@;
am__v_AR_1 = 
lib_libutils_a_AR = $(AR) $(ARFLAGS)
lib_libutils_a_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_lib_libutils_a_OBJECTS = src/utils/isax/lib_libutils_a-isax_first_buffer_layer.$(OBJEXT) \
	src/utils/isax/lib_libutils_a-isax_index.$(OBJEXT) \
	src/utils/isax/lib_libutils_a-isax_node.$(OBJEXT) \
	src/utils/isax/lib_libutils_a-isax_node_buffer.$(OBJEXT) \
	src/utils/isax/lib_libutils_a-isax_node_record.$(OBJEXT) \
	src/utils/isax/lib_libutils_a-isax_node_split.$(OBJEXT) \
	src/utils/isax/lib_libutils_a-pqueue.$(OBJEXT) \
	src/utils/sax/lib_libutils_a-sax.$(OBJEXT) \
	src/utils/sax/lib_libutils_a-ts.$(OBJEXT) \
	src/utils/lib_libutils_a-query_support.$(OBJEXT) \
	src/utils/lib_libutils_a-indexing_support.$(OBJEXT) \
	src/utils/lib_libutils_a-encoding_support.$(OBJEXT)
lib_libutils_a_OBJECTS = $(am_lib_libutils_a_OBJECTS)
am_bin_DETLSH_OBJECTS = src/main/bin_DETLSH-DETLSH.$(OBJEXT)
bin_DETLSH_OBJECTS = $(am_bin_DETLSH_OBJECTS)
bin_DETLSH_DEPENDENCIES =
bin_DETLSH_LINK = $(CXXLD) $(bin_DETLSH_CXXFLAGS) $(CXXFLAGS) \
	$(bin_DETLSH_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Po \
	src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Po \
	src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Po \
	src/utils/$(DEPDIR)/lib_libutils_a-query_support.Po \
	src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Po \
	src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Po \
	src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Po \
	src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Po \
	src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Po \
	src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Po \
	src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Po \
	src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Po \
	src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(lib_libutils_a_SOURCES) $(bin_DETLSH_SOURCES)
DIST_SOURCES = $(lib_libutils_a_SOURCES) $(bin_DETLSH_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP) \
	config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in AUTHORS \
	COPYING ChangeLog INSTALL NEWS README.md compile depcomp \
	install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} '/home/jiuqi/DET-LSH/missing' aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} '/home/jiuqi/DET-LSH/missing' autoconf
AUTOHEADER = ${SHELL} '/home/jiuqi/DET-LSH/missing' autoheader
AUTOMAKE = ${SHELL} '/home/jiuqi/DET-LSH/missing' automake-1.16
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O3
CPPFLAGS = 
CSCOPE = cscope
CTAGS = ctags
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O3
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
ETAGS = etags
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} '/home/jiuqi/DET-LSH/missing' makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = libutils
PACKAGE_BUGREPORT = weijiuqi19z@ict.ac.cn
PACKAGE_NAME = DET-LSH
PACKAGE_STRING = DET-LSH 1.0
PACKAGE_TARNAME = libutils
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.0
abs_builddir = /home/jiuqi/DET-LSH
abs_srcdir = /home/jiuqi/DET-LSH
abs_top_builddir = /home/jiuqi/DET-LSH
abs_top_srcdir = /home/jiuqi/DET-LSH
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/jiuqi/DET-LSH/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
lib_LIBRARIES = lib/libutils.a
lib_libutils_a_SOURCES = src/utils/isax/isax_first_buffer_layer.c src/utils/isax/isax_index.c src/utils/isax/isax_node.c src/utils/isax/isax_node_buffer.c src/utils/isax/isax_node_record.c src/utils/isax/isax_node_split.c src/utils/isax/pqueue.c src/utils/sax/sax.c src/utils/sax/ts.c src/utils/query_support.c src/utils/indexing_support.c src/utils/encoding_support.c
lib_libutils_a_CFLAGS = -I/opt/local/include -Iinclude/ -march=native -mavx -mavx2 -msse3 -fopenmp
bin_DETLSH_SOURCES = src/main/DETLSH.cpp
bin_DETLSH_CXXFLAGS = -I/opt/local/include -Iinclude/ -I/usr/local/include/ -march=native -fopenmp
bin_DETLSH_LDADD = -lm -lreadline -lutils -lpthread
bin_DETLSH_LDFLAGS = -L/opt/local/lib -Llib/  -march=native -mavx -mavx2 -msse3
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
install-libLIBRARIES: $(lib_LIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(INSTALL_DATA) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(INSTALL_DATA) $$list2 "$(DESTDIR)$(libdir)" || exit $$?; }
	@$(POST_INSTALL)
	@list='$(lib_LIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  if test -f $$p; then \
	    $(am__strip_dir) \
	    echo " ( cd '$(DESTDIR)$(libdir)' && $(RANLIB) $$f )"; \
	    ( cd "$(DESTDIR)$(libdir)" && $(RANLIB) $$f ) || exit $$?; \
	  else :; fi; \
	done

uninstall-libLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LIBRARIES)'; test -n "$(libdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(libdir)'; $(am__uninstall_files_from_dir)

clean-libLIBRARIES:
	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)
src/utils/isax/$(am__dirstamp):
	@$(MKDIR_P) src/utils/isax
	@: > src/utils/isax/$(am__dirstamp)
src/utils/isax/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/utils/isax/$(DEPDIR)
	@: > src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/isax/lib_libutils_a-isax_first_buffer_layer.$(OBJEXT):  \
	src/utils/isax/$(am__dirstamp) \
	src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/isax/lib_libutils_a-isax_index.$(OBJEXT):  \
	src/utils/isax/$(am__dirstamp) \
	src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/isax/lib_libutils_a-isax_node.$(OBJEXT):  \
	src/utils/isax/$(am__dirstamp) \
	src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/isax/lib_libutils_a-isax_node_buffer.$(OBJEXT):  \
	src/utils/isax/$(am__dirstamp) \
	src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/isax/lib_libutils_a-isax_node_record.$(OBJEXT):  \
	src/utils/isax/$(am__dirstamp) \
	src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/isax/lib_libutils_a-isax_node_split.$(OBJEXT):  \
	src/utils/isax/$(am__dirstamp) \
	src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/isax/lib_libutils_a-pqueue.$(OBJEXT):  \
	src/utils/isax/$(am__dirstamp) \
	src/utils/isax/$(DEPDIR)/$(am__dirstamp)
src/utils/sax/$(am__dirstamp):
	@$(MKDIR_P) src/utils/sax
	@: > src/utils/sax/$(am__dirstamp)
src/utils/sax/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/utils/sax/$(DEPDIR)
	@: > src/utils/sax/$(DEPDIR)/$(am__dirstamp)
src/utils/sax/lib_libutils_a-sax.$(OBJEXT):  \
	src/utils/sax/$(am__dirstamp) \
	src/utils/sax/$(DEPDIR)/$(am__dirstamp)
src/utils/sax/lib_libutils_a-ts.$(OBJEXT):  \
	src/utils/sax/$(am__dirstamp) \
	src/utils/sax/$(DEPDIR)/$(am__dirstamp)
src/utils/$(am__dirstamp):
	@$(MKDIR_P) src/utils
	@: > src/utils/$(am__dirstamp)
src/utils/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/utils/$(DEPDIR)
	@: > src/utils/$(DEPDIR)/$(am__dirstamp)
src/utils/lib_libutils_a-query_support.$(OBJEXT):  \
	src/utils/$(am__dirstamp) src/utils/$(DEPDIR)/$(am__dirstamp)
src/utils/lib_libutils_a-indexing_support.$(OBJEXT):  \
	src/utils/$(am__dirstamp) src/utils/$(DEPDIR)/$(am__dirstamp)
src/utils/lib_libutils_a-encoding_support.$(OBJEXT):  \
	src/utils/$(am__dirstamp) src/utils/$(DEPDIR)/$(am__dirstamp)
lib/$(am__dirstamp):
	@$(MKDIR_P) lib
	@: > lib/$(am__dirstamp)

lib/libutils.a: $(lib_libutils_a_OBJECTS) $(lib_libutils_a_DEPENDENCIES) $(EXTRA_lib_libutils_a_DEPENDENCIES) lib/$(am__dirstamp)
	$(AM_V_at)-rm -f lib/libutils.a
	$(AM_V_AR)$(lib_libutils_a_AR) lib/libutils.a $(lib_libutils_a_OBJECTS) $(lib_libutils_a_LIBADD)
	$(AM_V_at)$(RANLIB) lib/libutils.a
src/main/$(am__dirstamp):
	@$(MKDIR_P) src/main
	@: > src/main/$(am__dirstamp)
src/main/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/main/$(DEPDIR)
	@: > src/main/$(DEPDIR)/$(am__dirstamp)
src/main/bin_DETLSH-DETLSH.$(OBJEXT): src/main/$(am__dirstamp) \
	src/main/$(DEPDIR)/$(am__dirstamp)
bin/$(am__dirstamp):
	@$(MKDIR_P) bin
	@: > bin/$(am__dirstamp)

bin/DETLSH$(EXEEXT): $(bin_DETLSH_OBJECTS) $(bin_DETLSH_DEPENDENCIES) $(EXTRA_bin_DETLSH_DEPENDENCIES) bin/$(am__dirstamp)
	@rm -f bin/DETLSH$(EXEEXT)
	$(AM_V_CXXLD)$(bin_DETLSH_LINK) $(bin_DETLSH_OBJECTS) $(bin_DETLSH_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/main/*.$(OBJEXT)
	-rm -f src/utils/*.$(OBJEXT)
	-rm -f src/utils/isax/*.$(OBJEXT)
	-rm -f src/utils/sax/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Po # am--include-marker
include src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Po # am--include-marker
include src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Po # am--include-marker
include src/utils/$(DEPDIR)/lib_libutils_a-query_support.Po # am--include-marker
include src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Po # am--include-marker
include src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Po # am--include-marker
include src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Po # am--include-marker
include src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Po # am--include-marker
include src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Po # am--include-marker
include src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Po # am--include-marker
include src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Po # am--include-marker
include src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Po # am--include-marker
include src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/utils/isax/lib_libutils_a-isax_first_buffer_layer.o: src/utils/isax/isax_first_buffer_layer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_first_buffer_layer.o -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Tpo -c -o src/utils/isax/lib_libutils_a-isax_first_buffer_layer.o `test -f 'src/utils/isax/isax_first_buffer_layer.c' || echo '$(srcdir)/'`src/utils/isax/isax_first_buffer_layer.c
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Po
#	$(AM_V_CC)source='src/utils/isax/isax_first_buffer_layer.c' object='src/utils/isax/lib_libutils_a-isax_first_buffer_layer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_first_buffer_layer.o `test -f 'src/utils/isax/isax_first_buffer_layer.c' || echo '$(srcdir)/'`src/utils/isax/isax_first_buffer_layer.c

src/utils/isax/lib_libutils_a-isax_first_buffer_layer.obj: src/utils/isax/isax_first_buffer_layer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_first_buffer_layer.obj -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Tpo -c -o src/utils/isax/lib_libutils_a-isax_first_buffer_layer.obj `if test -f 'src/utils/isax/isax_first_buffer_layer.c'; then $(CYGPATH_W) 'src/utils/isax/isax_first_buffer_layer.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_first_buffer_layer.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Po
#	$(AM_V_CC)source='src/utils/isax/isax_first_buffer_layer.c' object='src/utils/isax/lib_libutils_a-isax_first_buffer_layer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_first_buffer_layer.obj `if test -f 'src/utils/isax/isax_first_buffer_layer.c'; then $(CYGPATH_W) 'src/utils/isax/isax_first_buffer_layer.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_first_buffer_layer.c'; fi`

src/utils/isax/lib_libutils_a-isax_index.o: src/utils/isax/isax_index.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_index.o -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Tpo -c -o src/utils/isax/lib_libutils_a-isax_index.o `test -f 'src/utils/isax/isax_index.c' || echo '$(srcdir)/'`src/utils/isax/isax_index.c
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Po
#	$(AM_V_CC)source='src/utils/isax/isax_index.c' object='src/utils/isax/lib_libutils_a-isax_index.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_index.o `test -f 'src/utils/isax/isax_index.c' || echo '$(srcdir)/'`src/utils/isax/isax_index.c

src/utils/isax/lib_libutils_a-isax_index.obj: src/utils/isax/isax_index.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_index.obj -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Tpo -c -o src/utils/isax/lib_libutils_a-isax_index.obj `if test -f 'src/utils/isax/isax_index.c'; then $(CYGPATH_W) 'src/utils/isax/isax_index.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_index.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Po
#	$(AM_V_CC)source='src/utils/isax/isax_index.c' object='src/utils/isax/lib_libutils_a-isax_index.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_index.obj `if test -f 'src/utils/isax/isax_index.c'; then $(CYGPATH_W) 'src/utils/isax/isax_index.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_index.c'; fi`

src/utils/isax/lib_libutils_a-isax_node.o: src/utils/isax/isax_node.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node.o -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node.o `test -f 'src/utils/isax/isax_node.c' || echo '$(srcdir)/'`src/utils/isax/isax_node.c
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node.c' object='src/utils/isax/lib_libutils_a-isax_node.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node.o `test -f 'src/utils/isax/isax_node.c' || echo '$(srcdir)/'`src/utils/isax/isax_node.c

src/utils/isax/lib_libutils_a-isax_node.obj: src/utils/isax/isax_node.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node.obj -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node.obj `if test -f 'src/utils/isax/isax_node.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node.c' object='src/utils/isax/lib_libutils_a-isax_node.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node.obj `if test -f 'src/utils/isax/isax_node.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node.c'; fi`

src/utils/isax/lib_libutils_a-isax_node_buffer.o: src/utils/isax/isax_node_buffer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node_buffer.o -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node_buffer.o `test -f 'src/utils/isax/isax_node_buffer.c' || echo '$(srcdir)/'`src/utils/isax/isax_node_buffer.c
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node_buffer.c' object='src/utils/isax/lib_libutils_a-isax_node_buffer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node_buffer.o `test -f 'src/utils/isax/isax_node_buffer.c' || echo '$(srcdir)/'`src/utils/isax/isax_node_buffer.c

src/utils/isax/lib_libutils_a-isax_node_buffer.obj: src/utils/isax/isax_node_buffer.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node_buffer.obj -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node_buffer.obj `if test -f 'src/utils/isax/isax_node_buffer.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node_buffer.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node_buffer.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node_buffer.c' object='src/utils/isax/lib_libutils_a-isax_node_buffer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node_buffer.obj `if test -f 'src/utils/isax/isax_node_buffer.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node_buffer.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node_buffer.c'; fi`

src/utils/isax/lib_libutils_a-isax_node_record.o: src/utils/isax/isax_node_record.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node_record.o -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node_record.o `test -f 'src/utils/isax/isax_node_record.c' || echo '$(srcdir)/'`src/utils/isax/isax_node_record.c
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node_record.c' object='src/utils/isax/lib_libutils_a-isax_node_record.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node_record.o `test -f 'src/utils/isax/isax_node_record.c' || echo '$(srcdir)/'`src/utils/isax/isax_node_record.c

src/utils/isax/lib_libutils_a-isax_node_record.obj: src/utils/isax/isax_node_record.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node_record.obj -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node_record.obj `if test -f 'src/utils/isax/isax_node_record.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node_record.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node_record.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node_record.c' object='src/utils/isax/lib_libutils_a-isax_node_record.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node_record.obj `if test -f 'src/utils/isax/isax_node_record.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node_record.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node_record.c'; fi`

src/utils/isax/lib_libutils_a-isax_node_split.o: src/utils/isax/isax_node_split.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node_split.o -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node_split.o `test -f 'src/utils/isax/isax_node_split.c' || echo '$(srcdir)/'`src/utils/isax/isax_node_split.c
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node_split.c' object='src/utils/isax/lib_libutils_a-isax_node_split.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node_split.o `test -f 'src/utils/isax/isax_node_split.c' || echo '$(srcdir)/'`src/utils/isax/isax_node_split.c

src/utils/isax/lib_libutils_a-isax_node_split.obj: src/utils/isax/isax_node_split.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-isax_node_split.obj -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Tpo -c -o src/utils/isax/lib_libutils_a-isax_node_split.obj `if test -f 'src/utils/isax/isax_node_split.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node_split.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node_split.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Po
#	$(AM_V_CC)source='src/utils/isax/isax_node_split.c' object='src/utils/isax/lib_libutils_a-isax_node_split.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-isax_node_split.obj `if test -f 'src/utils/isax/isax_node_split.c'; then $(CYGPATH_W) 'src/utils/isax/isax_node_split.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/isax_node_split.c'; fi`

src/utils/isax/lib_libutils_a-pqueue.o: src/utils/isax/pqueue.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-pqueue.o -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Tpo -c -o src/utils/isax/lib_libutils_a-pqueue.o `test -f 'src/utils/isax/pqueue.c' || echo '$(srcdir)/'`src/utils/isax/pqueue.c
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Po
#	$(AM_V_CC)source='src/utils/isax/pqueue.c' object='src/utils/isax/lib_libutils_a-pqueue.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-pqueue.o `test -f 'src/utils/isax/pqueue.c' || echo '$(srcdir)/'`src/utils/isax/pqueue.c

src/utils/isax/lib_libutils_a-pqueue.obj: src/utils/isax/pqueue.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/isax/lib_libutils_a-pqueue.obj -MD -MP -MF src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Tpo -c -o src/utils/isax/lib_libutils_a-pqueue.obj `if test -f 'src/utils/isax/pqueue.c'; then $(CYGPATH_W) 'src/utils/isax/pqueue.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/pqueue.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Tpo src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Po
#	$(AM_V_CC)source='src/utils/isax/pqueue.c' object='src/utils/isax/lib_libutils_a-pqueue.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/isax/lib_libutils_a-pqueue.obj `if test -f 'src/utils/isax/pqueue.c'; then $(CYGPATH_W) 'src/utils/isax/pqueue.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/isax/pqueue.c'; fi`

src/utils/sax/lib_libutils_a-sax.o: src/utils/sax/sax.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/sax/lib_libutils_a-sax.o -MD -MP -MF src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Tpo -c -o src/utils/sax/lib_libutils_a-sax.o `test -f 'src/utils/sax/sax.c' || echo '$(srcdir)/'`src/utils/sax/sax.c
	$(AM_V_at)$(am__mv) src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Tpo src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Po
#	$(AM_V_CC)source='src/utils/sax/sax.c' object='src/utils/sax/lib_libutils_a-sax.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/sax/lib_libutils_a-sax.o `test -f 'src/utils/sax/sax.c' || echo '$(srcdir)/'`src/utils/sax/sax.c

src/utils/sax/lib_libutils_a-sax.obj: src/utils/sax/sax.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/sax/lib_libutils_a-sax.obj -MD -MP -MF src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Tpo -c -o src/utils/sax/lib_libutils_a-sax.obj `if test -f 'src/utils/sax/sax.c'; then $(CYGPATH_W) 'src/utils/sax/sax.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/sax/sax.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Tpo src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Po
#	$(AM_V_CC)source='src/utils/sax/sax.c' object='src/utils/sax/lib_libutils_a-sax.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/sax/lib_libutils_a-sax.obj `if test -f 'src/utils/sax/sax.c'; then $(CYGPATH_W) 'src/utils/sax/sax.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/sax/sax.c'; fi`

src/utils/sax/lib_libutils_a-ts.o: src/utils/sax/ts.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/sax/lib_libutils_a-ts.o -MD -MP -MF src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Tpo -c -o src/utils/sax/lib_libutils_a-ts.o `test -f 'src/utils/sax/ts.c' || echo '$(srcdir)/'`src/utils/sax/ts.c
	$(AM_V_at)$(am__mv) src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Tpo src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Po
#	$(AM_V_CC)source='src/utils/sax/ts.c' object='src/utils/sax/lib_libutils_a-ts.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/sax/lib_libutils_a-ts.o `test -f 'src/utils/sax/ts.c' || echo '$(srcdir)/'`src/utils/sax/ts.c

src/utils/sax/lib_libutils_a-ts.obj: src/utils/sax/ts.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/sax/lib_libutils_a-ts.obj -MD -MP -MF src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Tpo -c -o src/utils/sax/lib_libutils_a-ts.obj `if test -f 'src/utils/sax/ts.c'; then $(CYGPATH_W) 'src/utils/sax/ts.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/sax/ts.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Tpo src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Po
#	$(AM_V_CC)source='src/utils/sax/ts.c' object='src/utils/sax/lib_libutils_a-ts.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/sax/lib_libutils_a-ts.obj `if test -f 'src/utils/sax/ts.c'; then $(CYGPATH_W) 'src/utils/sax/ts.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/sax/ts.c'; fi`

src/utils/lib_libutils_a-query_support.o: src/utils/query_support.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/lib_libutils_a-query_support.o -MD -MP -MF src/utils/$(DEPDIR)/lib_libutils_a-query_support.Tpo -c -o src/utils/lib_libutils_a-query_support.o `test -f 'src/utils/query_support.c' || echo '$(srcdir)/'`src/utils/query_support.c
	$(AM_V_at)$(am__mv) src/utils/$(DEPDIR)/lib_libutils_a-query_support.Tpo src/utils/$(DEPDIR)/lib_libutils_a-query_support.Po
#	$(AM_V_CC)source='src/utils/query_support.c' object='src/utils/lib_libutils_a-query_support.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/lib_libutils_a-query_support.o `test -f 'src/utils/query_support.c' || echo '$(srcdir)/'`src/utils/query_support.c

src/utils/lib_libutils_a-query_support.obj: src/utils/query_support.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/lib_libutils_a-query_support.obj -MD -MP -MF src/utils/$(DEPDIR)/lib_libutils_a-query_support.Tpo -c -o src/utils/lib_libutils_a-query_support.obj `if test -f 'src/utils/query_support.c'; then $(CYGPATH_W) 'src/utils/query_support.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/query_support.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/$(DEPDIR)/lib_libutils_a-query_support.Tpo src/utils/$(DEPDIR)/lib_libutils_a-query_support.Po
#	$(AM_V_CC)source='src/utils/query_support.c' object='src/utils/lib_libutils_a-query_support.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/lib_libutils_a-query_support.obj `if test -f 'src/utils/query_support.c'; then $(CYGPATH_W) 'src/utils/query_support.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/query_support.c'; fi`

src/utils/lib_libutils_a-indexing_support.o: src/utils/indexing_support.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/lib_libutils_a-indexing_support.o -MD -MP -MF src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Tpo -c -o src/utils/lib_libutils_a-indexing_support.o `test -f 'src/utils/indexing_support.c' || echo '$(srcdir)/'`src/utils/indexing_support.c
	$(AM_V_at)$(am__mv) src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Tpo src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Po
#	$(AM_V_CC)source='src/utils/indexing_support.c' object='src/utils/lib_libutils_a-indexing_support.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/lib_libutils_a-indexing_support.o `test -f 'src/utils/indexing_support.c' || echo '$(srcdir)/'`src/utils/indexing_support.c

src/utils/lib_libutils_a-indexing_support.obj: src/utils/indexing_support.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/lib_libutils_a-indexing_support.obj -MD -MP -MF src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Tpo -c -o src/utils/lib_libutils_a-indexing_support.obj `if test -f 'src/utils/indexing_support.c'; then $(CYGPATH_W) 'src/utils/indexing_support.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/indexing_support.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Tpo src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Po
#	$(AM_V_CC)source='src/utils/indexing_support.c' object='src/utils/lib_libutils_a-indexing_support.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/lib_libutils_a-indexing_support.obj `if test -f 'src/utils/indexing_support.c'; then $(CYGPATH_W) 'src/utils/indexing_support.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/indexing_support.c'; fi`

src/utils/lib_libutils_a-encoding_support.o: src/utils/encoding_support.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/lib_libutils_a-encoding_support.o -MD -MP -MF src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Tpo -c -o src/utils/lib_libutils_a-encoding_support.o `test -f 'src/utils/encoding_support.c' || echo '$(srcdir)/'`src/utils/encoding_support.c
	$(AM_V_at)$(am__mv) src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Tpo src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Po
#	$(AM_V_CC)source='src/utils/encoding_support.c' object='src/utils/lib_libutils_a-encoding_support.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/lib_libutils_a-encoding_support.o `test -f 'src/utils/encoding_support.c' || echo '$(srcdir)/'`src/utils/encoding_support.c

src/utils/lib_libutils_a-encoding_support.obj: src/utils/encoding_support.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -MT src/utils/lib_libutils_a-encoding_support.obj -MD -MP -MF src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Tpo -c -o src/utils/lib_libutils_a-encoding_support.obj `if test -f 'src/utils/encoding_support.c'; then $(CYGPATH_W) 'src/utils/encoding_support.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/encoding_support.c'; fi`
	$(AM_V_at)$(am__mv) src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Tpo src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Po
#	$(AM_V_CC)source='src/utils/encoding_support.c' object='src/utils/lib_libutils_a-encoding_support.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(lib_libutils_a_CFLAGS) $(CFLAGS) -c -o src/utils/lib_libutils_a-encoding_support.obj `if test -f 'src/utils/encoding_support.c'; then $(CYGPATH_W) 'src/utils/encoding_support.c'; else $(CYGPATH_W) '$(srcdir)/src/utils/encoding_support.c'; fi`

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/main/bin_DETLSH-DETLSH.o: src/main/DETLSH.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_DETLSH_CXXFLAGS) $(CXXFLAGS) -MT src/main/bin_DETLSH-DETLSH.o -MD -MP -MF src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Tpo -c -o src/main/bin_DETLSH-DETLSH.o `test -f 'src/main/DETLSH.cpp' || echo '$(srcdir)/'`src/main/DETLSH.cpp
	$(AM_V_at)$(am__mv) src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Tpo src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Po
#	$(AM_V_CXX)source='src/main/DETLSH.cpp' object='src/main/bin_DETLSH-DETLSH.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_DETLSH_CXXFLAGS) $(CXXFLAGS) -c -o src/main/bin_DETLSH-DETLSH.o `test -f 'src/main/DETLSH.cpp' || echo '$(srcdir)/'`src/main/DETLSH.cpp

src/main/bin_DETLSH-DETLSH.obj: src/main/DETLSH.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_DETLSH_CXXFLAGS) $(CXXFLAGS) -MT src/main/bin_DETLSH-DETLSH.obj -MD -MP -MF src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Tpo -c -o src/main/bin_DETLSH-DETLSH.obj `if test -f 'src/main/DETLSH.cpp'; then $(CYGPATH_W) 'src/main/DETLSH.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main/DETLSH.cpp'; fi`
	$(AM_V_at)$(am__mv) src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Tpo src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Po
#	$(AM_V_CXX)source='src/main/DETLSH.cpp' object='src/main/bin_DETLSH-DETLSH.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bin_DETLSH_CXXFLAGS) $(CXXFLAGS) -c -o src/main/bin_DETLSH-DETLSH.obj `if test -f 'src/main/DETLSH.cpp'; then $(CYGPATH_W) 'src/main/DETLSH.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main/DETLSH.cpp'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files
distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(LIBRARIES) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(libdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f bin/$(am__dirstamp)
	-rm -f lib/$(am__dirstamp)
	-rm -f src/main/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/main/$(am__dirstamp)
	-rm -f src/utils/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/utils/$(am__dirstamp)
	-rm -f src/utils/isax/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/utils/isax/$(am__dirstamp)
	-rm -f src/utils/sax/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/utils/sax/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Po
	-rm -f src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Po
	-rm -f src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Po
	-rm -f src/utils/$(DEPDIR)/lib_libutils_a-query_support.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Po
	-rm -f src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Po
	-rm -f src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f src/main/$(DEPDIR)/bin_DETLSH-DETLSH.Po
	-rm -f src/utils/$(DEPDIR)/lib_libutils_a-encoding_support.Po
	-rm -f src/utils/$(DEPDIR)/lib_libutils_a-indexing_support.Po
	-rm -f src/utils/$(DEPDIR)/lib_libutils_a-query_support.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_first_buffer_layer.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_index.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_buffer.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_record.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-isax_node_split.Po
	-rm -f src/utils/isax/$(DEPDIR)/lib_libutils_a-pqueue.Po
	-rm -f src/utils/sax/$(DEPDIR)/lib_libutils_a-sax.Po
	-rm -f src/utils/sax/$(DEPDIR)/lib_libutils_a-ts.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLIBRARIES

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	clean-libLIBRARIES cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip dist-zstd distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am \
	install-libLIBRARIES install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-libLIBRARIES

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
